### ISSUE TITLE
fix ./config.json reference when installed using npm

### ISSUE THREAD

**Issue by csanz** [csanz/node-nyam#1]
csanz:~ csanz$ nyam

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: EBADF, Bad file descriptor './config.json'
    at Object.openSync (fs.js:200:18)
    at Object.readFileSync (fs.js:91:15)
    at Object.<anonymous> (/usr/local/lib/node/.npm/nyam/0.0.2/package/lib/nyam.js:13:28)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at require (module.js:327:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/nyam/0.0.2/package/lib/cli.js:5:8)
    at Module._compile (module.js:383:26)

**Comment by csanz** [comment]
fixed, now fixing npm
