### ISSUE TITLE
"Error: No such module" when running "node cli.js -s"

### ISSUE THREAD

**Issue by sirkitree** [csanz/node-nyam#4]
```
$ node cli.js -s

[ Using override config at ~/.nyam_keys ]

:::::: we need to give this CLI tool access to yammer :::::::


Navigate to: https://www.yammer.com/oauth/authorize?oauth_token=...


/Users/sirkitree/github/node-nyam/lib/nyam.js:59
    , stdio = process.binding("stdio")
                      ^
Error: No such module
    at /Users/sirkitree/github/node-nyam/lib/nyam.js:59:23
    at /Users/sirkitree/github/node-nyam/lib/nyam.js:97:24
    at /Users/sirkitree/node_modules/oauth/lib/oauth.js:518:7
    at passBackControl (/Users/sirkitree/node_modules/oauth/lib/oauth.js:359:11)
    at IncomingMessage.<anonymous> (/Users/sirkitree/node_modules/oauth/lib/oauth.js:378:9)
    at IncomingMessage.emit (events.js:88:20)
    at HTTPParser.onMessageComplete (http.js:137:23)
    at CleartextStream.ondata (http.js:1124:24)
    at CleartextStream._push (tls.js:363:27)
    at SecurePair.cycle (tls.js:685:20)
```

**Comment by sirkitree** [comment]
Removed actual token.
